
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.provision "file", source: "mydaemon.service", destination: "~/mydaemon.service"

  config.vm.provision "shell", inline: <<-SHELL
    # Create test folders
    sudo mkdir /home/folder1/
    sudo mkdir /home/folder2/
    # Copy service file
    cat /home/vagrant/mydaemon.service > /etc/systemd/system/mydaemon.service
    # Reload all daemons
    systemctl daemon-reload
    # Run the daemon
    systemctl start mydaemon.service
    # Enable autostart
    systemctl enable mydaemon.service
    # Change directory to cron.d
    cd /etc/cron.d
    # Every minute during working days log logged in users to the file
    echo '* * * * 1-5 root w>>/var/log/logged-in.log' >mycron
    
   SHELL
end